source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Experience-Recorder_Example', :exclusive => true do
  pod "ExperienceRecorder", :path => "../"
end

target 'Experience-Recorder_Tests', :exclusive => true do
  pod "ExperienceRecorder", :path => "../"

  
end
